[package]
name = "immortal"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-lmdb = "0.44.0"
nostr-relay-builder = "0.44.0"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
